---
pulumi: # The pulumi project and stack could be derived from other abstracted values.
  project: OtherDevEnvironment
  stack: Mitch
vpc:
  cidr: 10.201.0.0/16
# db:
#   name: mitchdb
#   user: admin
#   password: Gerdisch419